### ISSUE TITLE
Compile a Mac Release

### ISSUE THREAD

**Issue by spencermacca** [LueWasHere/capsense#5]
I would really love a mac release please and thank you. I am an apple fanboy and need this for my 16-inch M1 Max Macbook Pro (1TB, Space Grey)

**Comment by Avenred** [comment]
Currently, Capsense is Windows only. I'm not sure how hard it would be to port to M1 Mac. @LueWasHere what do you think?

**Comment by LueWasHere** [comment]
It may be hard to put it on Mac since I don’t have one myself… but I could definitely try to whip one up in a couple of days…

**Comment by spencermacca** [comment]
> It may be hard to put it on Mac since I don’t have one myself… but I could definitely try to whip one up in a couple of days…

Appreciate it! thanks mate 👍

**Comment by LueWasHere** [comment]
Alright, I've added some code for darwin (macOS). I was hoping you could run it @SpencerComputers? As I said I don't have a mac and can't run it... If it does work, would you mind compiling it with the command provided in the README and sending me the resulting folder and compiled binary? Thanks.

**Comment by spencermacca** [comment]
Hey, installed all the dependencies and getting this error
```sh
smacca@Spencers-MacBook-Air capscontrol % python3 darwin.py           
Fetching preferences...
Done.
smacca@Spencers-MacBook-Air capscontrol % 
```

**Comment by LueWasHere** [comment]
You need to run ‘main.py’ it controls the logic for detecting your os and also properly running the darwin (or other os) file.

**Comment by LueWasHere** [comment]
If it works you should have a tray application (next to the clock I believe?) somewhere.

**Comment by Avenred** [comment]
I'd like to add that, in the current state, Capsense will not disable caps lock on Mac yet. We still have to figure out how to detect & disable caps lock on Mac. 
Currently we're just trying to figure out how to get a proper tray icon.

**Comment by spencermacca** [comment]
I do have a tray icon!
<img width="348" alt="image" src="https://user-images.githubusercontent.com/35679480/189786593-84a95d48-a050-4cc7-9153-ccbb92e5d737.png">

Of course I am getting an error but judging from what @Avenred said you probably know this, here's the error if you do need it though :)

```sh
Exception in thread Thread-1 (setup_handler):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/pystray/_base.py", line 394, in setup_handler
    setup(self)
  File "/Users/smacca/capsense/capscontrol/darwin.py", line 63, in main_loop
    while capslock_state() != 1:
  File "/Users/smacca/capsense/capscontrol/darwin.py", line 32, in capslock_state
    hll_dll = ctypes.WinDLL("User32.dll")
AttributeError: module 'ctypes' has no attribute 'WinDLL'
```

**Comment by Avenred** [comment]
That's great news! There's a new version of darwin.py that should hopefully fix caps detection on Mac. See if you can pull the latest commit and run the new code.

**Comment by LueWasHere** [comment]
Truly great news!

**Comment by LueWasHere** [comment]
New version added, using 'run.py' you should be able to run and use the program on MAC distributions.
I don't know if the program worked after my last commit for Darwin so let me know if this works or breaks anything that was previously working, and I will close this issue.
